### ISSUE TITLE
Fix announcement notification channel setting

### ISSUE THREAD

**Issue by voximity** [voximity/qubit-issues#13]
It's broken and I can't figure out why.

**Comment by miwilc** [comment]
Specifically on our server.

Here's the shameless plug:

<discord.io/heliohost>

**Comment by voximity** [comment]
I've seen it occurring elsewhere too (like on the Qubit server) but it seems to have fixed itself. Still unsure what causes it and I'm a little lazy to debug it right now.

**Comment by voximity** [comment]
After further examination, this appeared to be a bug with all channel types. RethinkDB was throwing a fit, cutting off some bits of the ulong I threw at it. I have switched to storing strings.
