### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by BaileyJM02** [voximity/qubit-issues#9]
A website is needed, I can use Jekyll to dynamically create one using Github, similar (or different) to [OctoJS](https://baileyjm02.github.io/OctoJS/).

Just @mention me on the Discord server if you need me too :+1:

**Comment by miwilc** [comment]
Eh. better to use the domain Qubit with be hosted on.

-1 for Jekyll. Use readthedocs.

**Comment by BaileyJM02** [comment]
You can still use the domain and github pages together with the CNAME

**Comment by voximity** [comment]
No need for a dynamically-created website. I'll serve a webpage through my React & Express setup unless you mean something else.

**Comment by minimand** [comment]
Make it in Twine

**Comment by voximity** [comment]
Closing issue. Will reopen if necessary. Web UI still isn't planned for a bit.
